import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {questions,makeReport} from '../lib/assessment.mjs';
const dir=await mkdtemp(join(tmpdir(),'root-tests-'));process.env.LOCAL_DATA_DIR=dir;process.env.WHATSAPP_MODE='preview';process.env.REVIEWER_API_KEY='test-reviewer-key';const {default:handler}=await import('../api/index.mjs');const server=createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;delete process.env.APP_URL;let cookie='';
async function req(path,body,options={}){const response=await fetch(base+'/api/'+path,{method:options.method||(body?'POST':'GET'),headers:{Origin:base,...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{}),...options.headers},body:body?JSON.stringify(body):undefined});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];const value=await response.json();return {response,value}}
const answers={name:'Kartik',age:'25–34',city:'Kolkata'};for(const q of questions)answers[q.id]=q.multi?[q.options.at(-1)==='None of these'?'None of these':q.options[0]]:q.options[0];answers.goals=['Control dandruff'];answers.safety=['Distinct bald patches'];answers.shedding='No';
test('full browser-session flow, ownership boundaries and mandatory fresh intake',async()=>{try{
let r=await req('session/start',{}, {headers:{Origin:'https://other-site.example'}});assert.equal(r.response.status,403,'cross-site requests stay blocked without APP_URL');
r=await req('assessments',{answers,consent:true});assert.equal(r.response.status,401);
r=await req('session/start',{});assert.equal(r.response.status,200);assert(cookie.startsWith('root_session='));assert(r.response.headers.get('set-cookie').includes('HttpOnly'));assert.equal(r.value.user.mode,'browser-session');assert(!r.value.user.phone);const sessionOwner=r.value.user.id,firstCookie=cookie;
r=await req('session/start',{});assert.equal(r.value.user.id,sessionOwner,'existing browser keeps its journey');assert.equal(cookie,firstCookie);
r=await req('auth/request',{phone:'9876543210',consent:true});assert.equal(r.response.status,404,'phone authentication removed');
r=await req('auth/verify',{challengeId:'unused',code:'123456'});assert.equal(r.response.status,404,'OTP endpoint removed');
r=await req('assessments',{answers,mediaIds:[],observations:[],consent:true});assert.equal(r.response.status,201);assert(r.value.report.referral);assert(r.value.report.products.length>0,'referral cannot remove recommendations');assert(r.value.report.gutContext);assert.equal(r.value.report.concerns[0].key,'Scalp','selected goal influences priority');const report=r.value.report;
r=await req('me');assert.equal(r.value.reports.length,1);
r=await req('bookings',{reportId:report.id,providerId:'coach',date:'2026-10-10',time:'10:00 AM',share:true,sharePhotos:true,whatsapp:false});assert.equal(r.response.status,201);const intake=r.value.intake;
r=await req('intakes/submit',{intakeId:intake.id,mediaIds:[],freshConsent:true});assert.equal(r.response.status,400,'missing photos/videos rejected');
const ids=[];for(const [n,angle]of ['front','top','crown','lengths'].entries()){const bytes=Buffer.from([255,216,255,224,n]);r=await req('media/prepare',{purpose:'personalised',kind:'photo',angle,intakeId:intake.id,contentType:'image/jpeg',size:bytes.length});assert.equal(r.response.status,201);const id=r.value.id;const upload=await fetch(base+'/api/media/local?id='+id,{method:'POST',headers:{Origin:base,Cookie:cookie},body:bytes});assert.equal(upload.status,200);ids.push(id)}
const video=Buffer.from([0,0,0,16,...Buffer.from('ftyp'),0,0,0,0]);r=await req('media/prepare',{purpose:'personalised',kind:'video',intakeId:intake.id,contentType:'video/mp4',size:video.length,duration:10});const videoId=r.value.id;const videoUpload=await fetch(base+'/api/media/local?id='+videoId,{method:'POST',headers:{Origin:base,Cookie:cookie},body:video});assert.equal(videoUpload.status,200);ids.push(videoId);
r=await req('intakes/submit',{intakeId:intake.id,mediaIds:ids,freshConsent:true});assert.equal(r.response.status,200);assert.equal(r.value.intake.status,'Submitted for review');
r=await req('admin/queue');assert.equal(r.response.status,403);
r=await req('admin/review',{intakeId:intake.id,reviewer:'Qualified reviewer',qualification:'Actual scope for test',note:'Personal notes recorded after review.',change:'Discuss the routine before changing actives.',followup:'2026-11-01'},{headers:{'X-Review-Key':'test-reviewer-key'}});assert.equal(r.response.status,200);
r=await req('me');assert.equal(r.value.reports.length,2);assert(r.value.reports[1].review);assert(!r.value.reports[0].review,'original report preserved');
const ownerCookie=cookie;cookie='';r=await req('session/start',{});assert.notEqual(r.value.user.id,sessionOwner,'new browser has a separate journey');const outsiderCookie=cookie;r=await req('reports/media?id='+report.id);assert.equal(r.response.status,404,'another account cannot read reports');const unauthorised=await fetch(base+'/api/media/read?id='+ids[0],{headers:{Cookie:outsiderCookie}});assert.equal(unauthorised.status,404);cookie=ownerCookie;
r=await req('reports/whatsapp',{reportId:report.id,consent:true});assert.equal(r.response.status,400,'delivery requires a separately provided number');
r=await req('reports/whatsapp',{reportId:report.id,phone:'9876543210',consent:false});assert.equal(r.response.status,400,'delivery remains opt-in');
r=await req('reports/whatsapp',{reportId:report.id,phone:'9876543210',consent:true});assert.equal(r.value.status,'prepared-not-sent');
r=await req('account',undefined,{method:'DELETE'});assert.equal(r.response.status,200);r=await req('me');assert.equal(r.response.status,401);
}finally{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true})}});
test('scoring remains illustrative and does not penalise unknown protein',()=>{const a=makeReport({...answers,protein:'With most meals'},[],false),b=makeReport({...answers,protein:'Not sure'},[],false);assert.equal(a.scores['Root support'],b.scores['Root support']);assert.equal(a.score,Math.round(Object.values(a.scores).reduce((s,n)=>s+n,0)/4))});
