import { mkdir, readFile, writeFile, unlink } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { get, put, list } from './store.mjs';
import { fail, validateMedia } from './validation.mjs';
export async function prepareMedia(user,metadata){const m=validateMedia(metadata);if(m.purpose==='personalised'){const intake=await get('intake',m.intakeId,user.id);if(!intake||intake.status!=='Awaiting fresh media')fail('Open your personalised-report intake before uploading.');}const id=randomUUID(),pathname=`root/${user.id}/${id}/${m.kind}`;const row={id,userId:user.id,purpose:m.purpose,kind:m.kind,angle:m.angle||null,intakeId:m.intakeId||null,pathname,contentType:m.contentType,size:m.size,duration:m.duration||null,maxBytes:m.maxBytes,status:'pending',createdAt:Date.now()};await put('media',id,user.id,row);return {id,pathname,storage:process.env.BLOB_READ_WRITE_TOKEN?'vercel-blob':'local-development'};}
function validMagic(buffer,type){if(type==='image/jpeg')return buffer[0]===0xff&&buffer[1]===0xd8;if(type==='image/png')return buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(type==='image/webp')return buffer.subarray(0,4).toString()==='RIFF'&&buffer.subarray(8,12).toString()==='WEBP';if(type==='video/webm')return buffer.subarray(0,4).equals(Buffer.from([26,69,223,163]));return buffer.subarray(4,8).toString()==='ftyp';}
export async function localUpload(user,id,bytes){if(process.env.VERCEL||process.env.NODE_ENV==='production')fail('Local upload storage is disabled in production.',503);const m=await get('media',id,user.id);if(!m||m.status!=='pending')fail('Invalid upload request.');if(bytes.length!==m.size||!validMagic(bytes,m.contentType))fail('File content or size does not match the declared format.');const hash=createHash('sha256').update(bytes).digest('hex');if(m.purpose==='personalised'){const previous=await list('media',user.id);if(previous.some(x=>x.hash===hash&&x.intakeId!==m.intakeId))fail('Please capture a fresh photo or video for this report booking.');}const dir=resolve(process.env.LOCAL_DATA_DIR||'.data','media');await mkdir(dir,{recursive:true});await writeFile(resolve(dir,id),bytes);m.hash=hash;m.status='ready';m.storage='local';m.uploadedAt=Date.now();await put('media',id,user.id,m);return {id,status:m.status};}
export async function confirmBlob(user,id,url){const m=await get('media',id,user.id);if(!m)fail('Upload not found.',404);if(!/^https:\/\/[a-zA-Z0-9.-]+\.blob\.vercel-storage\.com\//.test(url))fail('Invalid storage URL.');const { head }=await import('@vercel/blob');const blob=await head(url);if(!blob.pathname.startsWith(m.pathname)||blob.size!==m.size||blob.contentType!==m.contentType)fail('Upload details do not match this request.');m.storage='blob';m.url=blob.url;const content=await readMedia(m);if(!validMagic(content.bytes,m.contentType))fail('File content does not match its declared format.');m.hash=createHash('sha256').update(content.bytes).digest('hex');if(m.purpose==='personalised'){const previous=await list('media',user.id);if(previous.some(x=>x.id!==m.id&&x.hash===m.hash&&x.intakeId!==m.intakeId))fail('Please capture fresh media for this report booking.');}m.status='ready';m.uploadedAt=Date.now();await put('media',id,user.id,m);return {id,status:m.status};}
export async function uploadedMedia(user,ids,purpose,intakeId){if(!Array.isArray(ids)||ids.length>10||new Set(ids).size!==ids.length)fail('Invalid upload list.');return Promise.all(ids.map(async id=>{const m=await get('media',id,user.id);if(!m||m.status!=='ready'||m.purpose!==purpose||(intakeId&&m.intakeId!==intakeId))fail('Upload missing, incomplete or belongs to another report.');return m}));}
export async function readMedia(m){if(m.storage==='local'){if(process.env.VERCEL)fail('Local media unavailable.',404);return {bytes:await readFile(resolve(process.env.LOCAL_DATA_DIR||'.data','media',m.id)),contentType:m.contentType}}const {get:getBlob}=await import('@vercel/blob');const result=await getBlob(m.url,{access:'private'});if(!result||!result.stream)fail('Media unavailable.',404);return {bytes:Buffer.from(await new Response(result.stream).arrayBuffer()),contentType:m.contentType};}
export async function deleteMedia(m){if(m.storage==='local'){try{await unlink(resolve(process.env.LOCAL_DATA_DIR||'.data','media',m.id))}catch{}}else if(m.url){const {del}=await import('@vercel/blob');await del(m.url)}}
