import { randomUUID } from 'node:crypto';
import { requestOrigin as origin, checkRequestOrigin as checkOrigin } from '../lib/origin.mjs';
import { readFile } from 'node:fs/promises';
import { get, put, list, remove, removeOwner, database, rateLimit } from '../lib/store.mjs';
import { authenticate, startSession, phoneNumber, sessionCookie, cookie, sha, isReviewer, previewMode, twilio } from '../lib/auth.mjs';
import { makeReport, providers } from '../lib/assessment.mjs';
import { fail, text, validateAnswers, validateObservations } from '../lib/validation.mjs';
import { prepareMedia, localUpload, confirmBlob, uploadedMedia, readMedia, deleteMedia } from '../lib/media.mjs';
export const config={maxDuration:60};
const json=(res,status,value)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value))};
const error=e=>Object.assign(new Error(e),{status:400});
async function body(req,max=256*1024){if(req.body&&typeof req.body==='object'){if(Buffer.byteLength(JSON.stringify(req.body))>max)fail('Request is too large.',413);return req.body};const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)fail('Request is too large.',413);chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}')}catch{fail('Invalid JSON request.')}}
async function raw(req,max){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)fail('File is too large.',413);chunks.push(chunk)}return Buffer.concat(chunks)}
async function blobToken(req,res,b){const {handleUpload}=await import('@vercel/blob/client');const request=new Request(origin(req)+req.url,{method:'POST',headers:req.headers,body:JSON.stringify(b)});const result=await handleUpload({body:b,request,onBeforeGenerateToken:async(pathname,clientPayload)=>{const user=await authenticate(req);let info;try{info=JSON.parse(clientPayload||'{}')}catch{fail('Invalid upload payload.')}const m=await get('media',info.mediaId,user.id);if(!m||m.status!=='pending'||pathname!==m.pathname)fail('Unauthorised upload.',403);return {allowedContentTypes:[m.contentType],maximumSizeInBytes:m.maxBytes,addRandomSuffix:true,tokenPayload:JSON.stringify({mediaId:m.id,userId:user.id})}},onUploadCompleted:async({blob,tokenPayload})=>{const info=JSON.parse(tokenPayload),m=await get('media',info.mediaId,info.userId);if(!m||!blob.pathname.startsWith(m.pathname))throw error('Invalid upload callback.');m.url=blob.url;m.storage='blob';m.status=m.status==='ready'?'ready':'uploaded';m.uploadedAt=Date.now();await put('media',m.id,info.userId,m)}});json(res,200,result);}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');const url=new URL(req.url,'http://localhost:3000');const path=String(req.query?.path||url.searchParams.get('path')||url.pathname.replace(/^\/api\//,'')).replace(/^\/+|\/+$/g,'');try{
  // SDK validates the provider-signed Blob callback before any state changes.
  if(path==='media/token'&&req.method==='POST'){const b=await body(req);if(b.type!=='blob.upload-completed')checkOrigin(req);await blobToken(req,res,b);return}
  checkOrigin(req);
  if(path==='config'&&req.method==='GET'){json(res,200,{sessionMode:'browser',whatsappMode:previewMode()?'local-preview':'provider',storage:process.env.BLOB_READ_WRITE_TOKEN?'private-blob':'local-development',aiMode:'rules-based',providers:providers.map(p=>({...p,bookingStatus:'Request only'}))});return}
  if(path==='health'&&req.method==='GET'){try{await database();json(res,200,{ok:true})}catch{json(res,503,{ok:false,error:'Database unavailable. Configure DATABASE_URL and apply the migration.'})}return}
  if(path==='session/start'&&req.method==='POST'){const {token,user}=await startSession(req);if(token)res.setHeader('Set-Cookie',sessionCookie(token));json(res,200,{user:{id:user.id,mode:'browser-session',label:'This browser'}});return}
  if(path==='auth/request'||path==='auth/verify')fail('Endpoint not found.',404);
  if(path==='session/end'&&req.method==='POST'){const user=await authenticate(req);await remove('session',sha(cookie(req)),user.id);res.setHeader('Set-Cookie',sessionCookie('',true));json(res,200,{ok:true});return}
  if(path.startsWith('admin/')){if(!isReviewer(req))fail('Reviewer access required.',403);if(path==='admin/queue'&&req.method==='GET'){const queue=(await list('intake')).filter(x=>['Submitted for review','Reviewed'].includes(x.status));json(res,200,{intakes:queue});return}if(path==='admin/intake'&&req.method==='GET'){const id=url.searchParams.get('id');const intake=await get('intake',id);if(!intake)fail('Intake not found.',404);const booking=await get('booking',intake.bookingId,intake.userId),report=await get('report',intake.reportId,intake.userId);const media=await Promise.all((intake.mediaIds||[]).map(id=>get('media',id,intake.userId)));json(res,200,{intake,booking,report,media:media.map(m=>({id:m.id,kind:m.kind,angle:m.angle,contentType:m.contentType,url:`/api/media/read?id=${m.id}`}))});return}if(path==='admin/review'&&req.method==='POST'){const b=await body(req),intake=await get('intake',text(b.intakeId,'Intake ID',80));if(!intake||intake.status!=='Submitted for review')fail('This intake is not awaiting review.');const draft=await get('report',intake.reportId,intake.userId);if(!draft)fail('Baseline report unavailable.');const reviewed={...draft,id:'ROOT-'+randomUUID().slice(0,12).toUpperCase(),created:new Date().toISOString(),createdAt:Date.now(),draftId:draft.id,review:{reviewer:text(b.reviewer,'Reviewer name',80),qualification:text(b.qualification,'Qualification',160),note:text(b.note,'Personalised note',3000),change:text(b.change,'Agreed routine changes',2000),followup:text(b.followup,'Follow-up date',40),at:new Date().toISOString()},draftSnapshot:draft};if(!Number.isFinite(Date.parse(reviewed.review.followup)))fail('Invalid follow-up date.');await put('report',reviewed.id,intake.userId,reviewed);intake.status='Reviewed';intake.reviewedReportId=reviewed.id;await put('intake',intake.id,intake.userId,intake);json(res,200,{reportId:reviewed.id});return}fail('Unknown reviewer action.',404)}
  if(path==='media/read'&&req.method==='GET'){const id=url.searchParams.get('id');const m=isReviewer(req)?await get('media',id):await get('media',id,(await authenticate(req)).id);if(!m)fail('Media not found.',404);const media=await readMedia(m);res.statusCode=200;res.setHeader('Content-Type',media.contentType);res.setHeader('Content-Disposition','inline');res.setHeader('Accept-Ranges','bytes');let bytes=media.bytes;const range=req.headers.range;if(range){const match=/^bytes=(\d+)-(\d*)$/.exec(range);if(!match)fail('Unsupported byte range.',416);const start=Number(match[1]),end=match[2]?Number(match[2]):bytes.length-1;if(start>=bytes.length||end<start)fail('Invalid byte range.',416);const last=Math.min(end,bytes.length-1);res.statusCode=206;res.setHeader('Content-Range',`bytes ${start}-${last}/${bytes.length}`);bytes=bytes.subarray(start,last+1)}for(let offset=0;offset<bytes.length;offset+=65536){if(!res.write(bytes.subarray(offset,offset+65536)))await new Promise(resolve=>res.once('drain',resolve))}res.end();return}
  const user=await authenticate(req);
  if(path==='intakes/media'&&req.method==='GET'){const intake=await get('intake',url.searchParams.get('id'),user.id);if(!intake)fail('Intake not found.',404);const media=(await list('media',user.id)).filter(x=>x.intakeId===intake.id&&x.status==='ready');json(res,200,{media:media.map(m=>({id:m.id,kind:m.kind,angle:m.angle}))});return}
  if(path==='reports/media'&&req.method==='GET'){const report=await get('report',url.searchParams.get('id'),user.id);if(!report)fail('Report not found.',404);const media=await Promise.all((report.mediaIds||[]).map(id=>get('media',id,user.id)));json(res,200,{media:media.filter(Boolean).map(m=>({id:m.id,kind:m.kind,angle:m.angle}))});return}
  if(path==='me'&&req.method==='GET'){json(res,200,{user:{id:user.id,mode:'browser-session',label:'This browser'},reports:await list('report',user.id),bookings:await list('booking',user.id),intakes:await list('intake',user.id)});return}
  if(path==='assessments'&&req.method==='POST'){const b=await body(req);if(b.consent!==true)fail('Consent to store this assessment is required.');const answers=validateAnswers(b.answers),observations=validateObservations(b.observations);const media=await uploadedMedia(user,b.mediaIds||[],'assessment');if(observations.length&&!media.length)fail('Photo observations need an uploaded image.');const report=makeReport(answers,observations,false);report.mediaIds=media.map(m=>m.id);report.createdAt=Date.now();report.consent={assessment:true,at:new Date().toISOString()};report.checkin=b.checkin?{comfort:text(b.checkin.comfort,'Comfort',80),adherence:text(b.checkin.adherence,'Adherence',80),note:text(b.checkin.note,'Note',500,true)}:null;await put('report',report.id,user.id,report);await put('profile',user.id,user.id,{id:user.id,name:answers.name,gender:answers.gender,age:answers.age,city:answers.city,updatedAt:Date.now()});json(res,201,{report});return}
  if(path==='reports/kit'&&req.method==='POST'){const b=await body(req),r=await get('report',b.reportId,user.id);if(!r)fail('Report not found.',404);if(!Array.isArray(b.keys)||b.keys.some(k=>!r.products.some(p=>p.key===k)))fail('Invalid product selection.');r.selectedProductKeys=[...new Set(b.keys)];await put('report',r.id,user.id,r);json(res,200,{report:r});return}
  if(path==='media/prepare'&&req.method==='POST'){const result=await prepareMedia(user,await body(req));json(res,201,result);return}
  if(path==='media/local'&&req.method==='POST'){const id=url.searchParams.get('id'),m=await get('media',id,user.id);if(!m)fail('Upload not found.',404);json(res,200,await localUpload(user,id,await raw(req,m.maxBytes)));return}
  if(path==='media/confirm'&&req.method==='POST'){const b=await body(req);json(res,200,await confirmBlob(user,b.id,text(b.url,'Storage URL',1000)));return}
  if(path==='bookings'&&req.method==='POST'){const b=await body(req),p=providers.find(x=>x.id===b.providerId);if(!p)fail('Invalid care option.');const report=await get('report',b.reportId,user.id);if(!report)fail('Complete an assessment before booking a personalised report.');const date=text(b.date,'Date',10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date+'T23:59:59+05:30')<new Date())fail('Choose an upcoming date.');if(!['10:00 AM','12:30 PM','04:00 PM','06:30 PM'].includes(b.time))fail('Invalid slot.');const prior=await list('booking',user.id);if(prior.some(x=>x.providerId===p.id&&x.date===date&&x.time===b.time&&x.status!=='Cancelled'))fail('You already requested this slot.',409);if(b.share!==true||b.sharePhotos!==true)fail('A personalised report requires your consent to share the report and fresh media with its reviewer.');const booking={id:'BOOK-'+randomUUID().slice(0,12),userId:user.id,name:report.name,date,time:b.time,providerId:p.id,reportId:report.id,note:text(b.note,'Question',500,true),share:true,sharePhotos:true,whatsapp:b.whatsapp===true,status:'Awaiting fresh media',createdAt:Date.now(),created:new Date().toISOString(),fee:p.fee,timezone:'Asia/Kolkata'};const intake={id:randomUUID(),userId:user.id,bookingId:booking.id,reportId:report.id,status:'Awaiting fresh media',mediaIds:[],consentAt:new Date().toISOString(),createdAt:Date.now()};booking.intakeId=intake.id;await put('booking',booking.id,user.id,booking);await put('intake',intake.id,user.id,intake);json(res,201,{booking,intake});return}
  if(path==='bookings/cancel'&&req.method==='POST'){const b=await body(req),booking=await get('booking',b.id,user.id);if(!booking)fail('Booking not found.',404);booking.status='Cancelled';await put('booking',booking.id,user.id,booking);const intake=await get('intake',booking.intakeId,user.id);if(intake){intake.status='Cancelled';await put('intake',intake.id,user.id,intake)}json(res,200,{ok:true});return}
  if(path==='intakes/submit'&&req.method==='POST'){const b=await body(req),intake=await get('intake',b.intakeId,user.id);if(!intake||intake.status!=='Awaiting fresh media')fail('This report intake is not awaiting uploads.');const media=await uploadedMedia(user,b.mediaIds,'personalised',intake.id);const photos=media.filter(x=>x.kind==='photo'),videos=media.filter(x=>x.kind==='video');if(!['front','top','crown','lengths'].every(angle=>photos.some(p=>p.angle===angle))||!videos.length)fail('A personalised report needs fresh front, top, crown and lengths photos plus a 5–60 second video.');if(media.some(x=>x.createdAt<intake.createdAt))fail('Capture new media after this report was booked.');if(b.freshConsent!==true)fail('Confirm that these photos and videos were freshly captured.');intake.mediaIds=media.map(x=>x.id);intake.status='Submitted for review';intake.freshConsentAt=new Date().toISOString();intake.submittedAt=Date.now();await put('intake',intake.id,user.id,intake);const booking=await get('booking',intake.bookingId,user.id);booking.status='Report requested';await put('booking',booking.id,user.id,booking);json(res,200,{intake,booking});return}
  if(path==='reports/whatsapp'&&req.method==='POST'){const b=await body(req),r=await get('report',b.reportId,user.id);if(!r)fail('Report not found.',404);if(b.consent!==true)fail('Consent is required for WhatsApp report delivery.');const recipient=phoneNumber(b.phone);if(!await rateLimit('report-send:'+user.id,5,3600000))fail('Too many report requests. Try again later.',429);if(previewMode()){json(res,200,{status:'prepared-not-sent',demo:true});return}if(!process.env.TWILIO_WHATSAPP_FROM||!process.env.TWILIO_REPORT_CONTENT_SID)fail('WhatsApp report delivery needs an approved template and configured sender.',503);const link=new URL('/?report='+encodeURIComponent(r.id)+'#report',origin(req)).toString();const result=await twilio('Messages',{To:'whatsapp:'+recipient,From:process.env.TWILIO_WHATSAPP_FROM,ContentSid:process.env.TWILIO_REPORT_CONTENT_SID,ContentVariables:JSON.stringify({'1':r.name,'2':link})});await put('message',result.sid,user.id,{id:result.sid,reportId:r.id,recipientMasked:'••••••'+recipient.slice(-4),status:result.status,consentAt:new Date().toISOString(),createdAt:Date.now()});json(res,200,{status:result.status,id:result.sid});return}
  if(path==='account'&&req.method==='DELETE'){const media=await list('media',user.id);await Promise.all(media.map(deleteMedia));await removeOwner(user.id);res.setHeader('Set-Cookie',sessionCookie('',true));json(res,200,{ok:true});return}
  fail('Endpoint not found.',404);
}catch(e){const status=e.status||500;if(status>=500)console.error('ROOT API error:',path,e.name);json(res,status,{error:status===500?'The request could not be completed. Please check the backend configuration.':e.message})}}
